# Generated by Django 5.0.1 on 2024-02-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='img_name',
        ),
        migrations.AddField(
            model_name='picture',
            name='file',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
