# Generated by Django 5.0.1 on 2024-02-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_picture_img_name_picture_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='file',
        ),
        migrations.AddField(
            model_name='picture',
            name='img_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
