from app.moduls._customers import customers_serializer
from app.moduls._customers_orders import customers_orders_serializer
from app.moduls._products import products_serializer
from app.moduls._products_categories import products_categories_serializer
from app.moduls._test_img import test_img_serializer